# This script was generated by the ERD tool in pgAdmin 4.
db_setup_script = '''
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    "UserID" serial NOT NULL,
    "Name" character varying(64) NOT NULL,
    "Age" integer NOT NULL,
    "Email" character varying(64) NOT NULL,
    CONSTRAINT "UserID" PRIMARY KEY ("UserID")
);

CREATE TABLE IF NOT EXISTS public."Resume"
(
    "ResumeID" serial NOT NULL,
    "Name" character varying(64) NOT NULL,
    "File_Link" text NOT NULL,
    "OwnerID" serial NOT NULL,
    CONSTRAINT "ResumeID" PRIMARY KEY ("ResumeID")
);

CREATE TABLE IF NOT EXISTS public."Vacancy"
(
    "VacancyID" serial NOT NULL,
    "Name" character varying(64) NOT NULL,
    "Description" character varying(4096),
    "Creation_Date" timestamp without time zone NOT NULL,
    "PublisherID" serial NOT NULL,
    CONSTRAINT "VacancyID" PRIMARY KEY ("VacancyID")
);

CREATE TABLE IF NOT EXISTS public."ResumeVacancy"
(
    "ResumeID" serial NOT NULL,
    "VacancyID" serial NOT NULL,
    CONSTRAINT "Resume-Vacancy" PRIMARY KEY ("ResumeID", "VacancyID")
);

ALTER TABLE IF EXISTS public."Resume"
    ADD CONSTRAINT "OwnerID" FOREIGN KEY ("OwnerID")
    REFERENCES public."User" ("UserID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Vacancy"
    ADD CONSTRAINT "PublisherID" FOREIGN KEY ("PublisherID")
    REFERENCES public."User" ("UserID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."ResumeVacancy"
    ADD CONSTRAINT "ResumeID" FOREIGN KEY ("ResumeID")
    REFERENCES public."Resume" ("ResumeID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."ResumeVacancy"
    ADD CONSTRAINT "VacancyID" FOREIGN KEY ("VacancyID")
    REFERENCES public."Vacancy" ("VacancyID") MATCH SIMPLE 
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;
'''